### ISSUE TITLE
I have a error: can't decode byte 0xc5

### ISSUE THREAD

**Issue by bs111** [dsch/gsm0338#8]
**I have a Modem Log from Phone. i Open it from Qcom tools.
when i get the hex data to translate it. it has an error.**

**setp:**
1.the TP_user_data is : "6376783E07C500" from the Qcom tools.
2. I used the following ：
C:\Users\borla>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gsm0338
>>> hexcode="6376783E07C500"
>>> gsmcode=bytes.fromhex(hexcode)
>>> print(gsmcode.hex())
6376783e07c500
>>> gsmcode.decode('gsm03.38')
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\gsm0338\codec.py", line 75, in decode
    decode_buffer += unichr(self._decode_map[num])
KeyError: 197

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\gsm0338\codec.py", line 87, in decode
    (self.NAME, ex.args[0], consumed - 1))
ValueError: 'gsm03.38' codec can't decode byte 0xc5 in position 5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: decoding with 'gsm03.38' codec failed (ValueError: 'gsm03.38' codec can't decode byte 0xc5 in position 5)
>>>

**expact result**
"class 1" as the  Qcom tools decode.    

**version:**
gsm0338          1.0.0
win10 pro 1903
python 3.7

**modem information**
**_1.the hex information:_**
[0x713A/009/001]         OTA LOG                  01:26:30.978             SMS/CP Data              Direction : Network To MSLength: 42                         0x10003b003b003a710008cedd4172bf00002a000000690127016f0891683110301405f0001a040ba15156813926f8001121801090625323076376783e07c500
**_2.the picture decode from QC tools:_**

**Comment by bs111** [comment]
![Uploading 1短信的pdu解析-使用python2的模块.py.PNG…]()

**Comment by bs111** [comment]
![1短信的pdu解析-使用python2的模块](https://user-images.githubusercontent.com/38519076/66733773-2a5f4280-ee93-11e9-8d5c-83e27dc05ccb.gif)

**Comment by dsch** [comment]
Your data is 7-bit packed as specified by [GSM 03.40](https://en.wikipedia.org/wiki/GSM_03.40). But the gsm03.38 codec only supports unpacked data (octets). Therefor your TPDU decoder has to properly unpack the data into single bytes before you could decode it with the codec.

For your example data that could look like this:
```
import gsm0338

length = 7  # length of 7-bit units (TP-UDL)
data = bytes.fromhex('6376783E07C500')  # user data (TP-UD)
octets = bytearray(length)
c = 0
b = 0
it = iter(data)
for i in range(length):
    if c < 7:
        b |= next(it) << c
        c += 8
    octets[i] = b & 0x7F
    b >>= 7
    c -= 7

assert octets.decode('GSM03.38') == 'class 1'
```

**Comment by bs111** [comment]
OK tks
